---
- name: Install Java and Aerospike on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Update apt package list
      apt:
        update_cache: yes

    - name: Install OpenJDK 8 (required for Aerospike)
      apt:
        name: openjdk-8-jdk
        state: present

    - name: Download and install Aerospike repository
      shell: curl -s https://packages.aerospike.com/gpg/ | apt-key add -
    
    - name: Add Aerospike repository
      shell: echo "deb https://packages.aerospike.com/debian/ ubuntu main" | tee -a /etc/apt/sources.list.d/aerospike.list

    - name: Update apt package list again after adding Aerospike repo
      apt:
        update_cache: yes

    - name: Install Aerospike server
      apt:
        name: aerospike-server
        state: present

    - name: Start Aerospike service
      systemd:
        name: aerospike
        state: started
        enabled: yes

    - name: Check status of Aerospike service
      systemd:
        name: aerospike
        state: started

